FROM node:16.19.1-alpine3.17

# For development add /bin/bash
RUN apk update && apk add --no-cache bash

# Set up the server directory
WORKDIR /app
COPY . /app

# Install yarn dependencies
RUN yarn install --network-timeout 100000
RUN yarn build

# Run `yarn docker` to build, migrate and run the server with pm2.
CMD ["yarn", "dev"]
